# mamba env create -f environment.yml
name: pydfcsr
channels:
  - conda-forge
dependencies:
  - python=3.12
  - distgen
  - h5py
  - ipympl
  - pytorch
  - jupyterlab
  - matplotlib
  - mpi4py
  - numba
  - numpy <2
  - pyyaml
  - pytest
  - scipy
  - pip
  - pip:
      # Install this package as well
      - .
      # Install bmad-x from git until it's available on conda-forge:
      - git+https://github.com/bmad-sim/Bmad-X/
